### ISSUE TITLE
Pause game crash...

### ISSUE THREAD

**Issue by Andy8463** [geode-sdk/NodeIDs#7]
The game crashes if i pause it.

**Comment by relaxingOcean** [comment]
same for me

**Comment by MrNooberDude** [comment]
crashlog:
[2024-02-06_05-40-37.log](https://github.com/geode-sdk/NodeIDs/files/14178409/2024-02-06_05-40-37.log)

**Comment by Cvolton** [comment]
does the issue persist on v1.2.4?

**Comment by MrNooberDude** [comment]
it also doesn't happen on Android though.

**Comment by CM4KGaming** [comment]
The crash happens when gaining points in platformer mode for some reason.
![Screenshot_2024-02-07-06-38-19-68_73932565f5d18c5d7f2b58eb6d5de17f](https://github.com/geode-sdk/NodeIDs/assets/159200219/e645556b-5842-4ed5-af32-35f04844ef83)
![Screenshot_2024-02-07-06-38-22-34_73932565f5d18c5d7f2b58eb6d5de17f](https://github.com/geode-sdk/NodeIDs/assets/159200219/669490c3-6152-464a-9f3b-c713ffe7768c)
![Screenshot_2024-02-07-06-38-28-05_73932565f5d18c5d7f2b58eb6d5de17f](https://github.com/geode-sdk/NodeIDs/assets/159200219/94fbd771-7965-4c15-841d-6df88f124af8)

**Comment by Cvolton** [comment]
this is fixed in 2c4dca90a507e1ac8a9e1d5f75f3866caf6057dc , awaiting release

**Comment by MrNooberDude** [comment]
It works now! Should probably close issue.

**Comment by Cvolton** [comment]
marking as resolved, can reopen if needed
